### ISSUE TITLE
Pug?

### ISSUE THREAD

**Issue by Not-ANinja** [rajasegar/JADE-Bootstrap#11]
Update documentation to use Pug.
Thanks

**Comment by rajasegar** [comment]
As per the pugjs/pug repository, 

> Pug 2.0.0 is still under alpha stage, and there are several syntactic differences we have deprecated and removed. Such differences are documented at #2305. The website and documentation for Pug are still being updated, but if you are new to Pug, you should get started with the new syntax and install the Pug package on npm.

So, will be updating the documentation as soon as Pug's is updated...

**Comment by Not-ANinja** [comment]
Oh neat!

**Comment by mike-goodwin** [comment]
I needed to upgrade to pug for my project but I get why you don't want to yet. So, I made a fork and upgraded it myself. I fixed up all the unit tests to account for the breaking changes between jade and pug - but the unit tests don't cover everything and I didn't fix up areas where there are no tests.

The new repo is here: https://github.com/mike-goodwin/pug-bootstrap

And I published an npm package here: https://www.npmjs.com/package/pug-bootstrap

When you decide it's the right time to move to pug, feel free to use my fork as a starting point if you like - it might save you a few hours. I don't want to maintain a parallel version once you do upgrade, so please can you let me know when you do and I will switch back to your "official" version :)

**Comment by 256k** [comment]
small suggestion to change the name from jade-bootstrap to "JadeStrap" and/or pug-bootstrap to "PugStrap"

**Comment by justjoeyuk** [comment]
So... pug?

**Comment by rajasegar** [comment]
Apologies for the delay,
@256k  @justjoeyuk Just now migrated to pug, will be working on the name changes and documentation , will update you guys once done

**Comment by mike-goodwin** [comment]
That's good news. In my fork I added a bunch of unit tests (almost 100% coverage in fact). Please contact me if you are interested in merging these into your repo.

https://github.com/mike-goodwin/pug-bootstrap
