### ISSUE TITLE
Indentation Error for JADE

### ISSUE THREAD

**Issue by 24X7** [rajasegar/JADE-Bootstrap#13]
@rajasegar - I did an NPM install just two days ago.  I am seeing the error below:

node_modules/jade-bootstrap/components/forms.jade:20 18| //- Checkbox - Inline style 19| mixin checkbox-inline(text,name,id) > 20| .checkbox-inline 21| input(type="checkbox",name="#{name}",id="#{id}") 22| = text 23| Invalid indentation, you can use tabs or spaces but not both

My pug template is just extending _bootstrap.

**Comment by rajasegar** [comment]
Fixed in this
https://github.com/rajasegar/JADE-Bootstrap/commit/436c49a9b7d36da17048e732c59e4ddfde217437
