### ISSUE TITLE
Insert Image to navbar brand

### ISSUE THREAD

**Issue by kenanchristian** [rajasegar/JADE-Bootstrap#17]
Hi, It's a awesome plugin for jade.
My question is, how can I use a image on the navbar-brand?

**Comment by rajasegar** [comment]
@kenanchristian , you can now use the new mixin for navbar called
navbar-logo(name, id, style, href, image)
where name = alt text for the logo
image = src url for the brand image 
kindly refer to bootstrap docs  http://getbootstrap.com/components/#navbar-brand-image

**Comment by kenanchristian** [comment]
@rajasegar Thanks for the fast response, but i think something broken on your code..

This is my code
![image](https://cloud.githubusercontent.com/assets/11202498/19417234/a44ec842-93d1-11e6-9a57-80b111038a7b.png)

This is what i get
![image](https://cloud.githubusercontent.com/assets/11202498/19417238/c3f65a20-93d1-11e6-813d-6bdef5f483b4.png)

I also create a pull request(#19), but with that changes, it doesn't seems to be

**Comment by kenanchristian** [comment]
already included the fix inside pull request :)
you forgot to add `ul.nav.navbar-nav`
