### ISSUE TITLE
Invalid indentation

### ISSUE THREAD

**Issue by fmadotto** [rajasegar/JADE-Bootstrap#18]
Since the latest commit, there are these invalid indentations that needs to be fixed:
* In `components/navbar.jade` at line 31 (indentation with spaces instead of tabs)
* In `components/panels.jade` from line 3 to 11 (indentation with spaces instead of tabs)

In addition to that, the navbar seems broken (elements not showing up correctly. Issue showing up also in the [jadebootstrap-seed boilerplate](https://github.com/rajasegar/jadebootstrap-seed) for Node.js.

**Comment by kenanchristian** [comment]
@fmadotto for this repo, I fixed it all on my pull request (#19). But i haven't checked on the `jadebootstrap-seed boilerplate` yet

**Comment by fmadotto** [comment]
I was going to submit a pull request identical to yours, and I tested it with the boilerplate: it works.
Cheers.
