### ISSUE TITLE
Can't work with quickstart

### ISSUE THREAD

**Issue by gh286991** [rajasegar/JADE-Bootstrap#20]
Hi

I am following the steps of quick start but show error with below.

Can I ask how can I fix with this problem, Thank you

image
![image](https://cloud.githubusercontent.com/assets/22841659/19487024/6214b086-9593-11e6-8ed0-c9ea4f397f9f.png)

**Comment by rajasegar** [comment]
@gh286991 Can you please check with the latest version 1.0.8 and let me know , i just rolled out a fix
