### ISSUE TITLE
NPM Package of fixed version?

### ISSUE THREAD

**Issue by southpawlife** [rajasegar/JADE-Bootstrap#6]
I was looking to consume the fix with the name field added to the input mixin's, were you planning to publish a new version to the npm repo?

Cheers!

**Comment by rajasegar** [comment]
I just published v1.0.2 with the name filed fixes, you can use it now...

On Sat, Feb 27, 2016 at 1:21 PM, Kristopher Williams <
notifications@github.com> wrote:

> I was looking to consume the fix with the name field added to the input
> mixin's, were you planning to publish a new version to the npm repo?
>
> Cheers!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rajasegar/JADE-Bootstrap/issues/6>.
>



-- 
Regards & Thanks,
Rajasegar Chandiran
www.hangaroundtheweb.com

**Comment by southpawlife** [comment]
Cheers, thanks! :+1:
